application: Stillpoint
psr4: 'app/Stillpoint'
processed: false
dependencies: 
    flash: 
        enabled: true
        repo: 'laracasts/flash'
        provider: flash_provider
        alias: flash_alias
    html:
        enabled: true
        repo: 'illuminate/html'
        provider: html_provider
        alias: html_alias
    presenter:
        enabled: true
        repo: 'laracasts/presenter'
        provider: presenter_provider
        alias: presenter_alias
    debugbar:
        enabled: true
        repo: 'barryvdh/laravel-debugbar' 
        provider: debugbar_provider
        alias: debugbar_alias
    glide: 
        enabled: true
        repo: 'league/glide'
        provider: glide_provider
        alias: glide_alias
    medialibrary:
        enabled: true
        repo: 'spatie/laravel-medialibrary'
        provider: medialibrary_provider
        alias: medialibrary_alias
entities:
      - name: News
        processed: false
        model: true
        relationships:
          - type: hasMany
            model: Photos
            key1: album_id
            key2: 
        migration: true
        scaffold: true
        presentable: true
        media: true
        repository: true
        commands: true
        events: true
        controller: true
        requests: true
        admin:
            enabled: true
            scaffold: true
        routes: true
        fields:
            - name: title
              type: string
              nullable: false
              default: false
              default_value: false
            - name: slug
              type: string
              nullable: false
              default: false
              default_value: false
            - name: excerpt
              type: text
              nullable: false
              default: false
              default_value: false
            - name: body
              type: text
              nullable: false
              default: false
              default_value: false
            - name: featured_photo_id
              type: integer
              nullable: true
              default: true
              default_value: false